### ISSUE TITLE
Have you put the ucsc tools up on galaxy in the main tool shed? 

### ISSUE THREAD

**Issue by alexlenail** [sidiropoulos/galaxy-tools#1]
If so, what's your name on there? It isn't `sidiropoulos` I don't think. If not, why not? Are there other implementations of these ucsc tools (e.g. `bedclip`) that are better maintained?

**Comment by sidiropoulos** [comment]
Hi! The tools are available in the [TestToolshed](https://testtoolshed.g2.bx.psu.edu) only (username nikos). I implemented them about two years ago for a local galaxy distribution and added them on the toolshed to learn and test its' functionality. 

As far as I remember, installing them from the toolshed worked fine but I need to revisit the code and the updates in galaxy in general before I push them to the Main Tool Shed. 

I don't maintain any of these tools and my focus is other areas at the moment. If there are any updates I will make sure to notify you. :)
